In [38]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

data=pd.read_csv("health_lifestyle_classification.csv")
data

,survey_code,age,gender,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,...,sunlight_exposure,meals_per_day,caffeine_intake,family_history,pet_owner,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage,target
0,1,56,Male,173.416872,56.886640,18.915925,18.915925,56.747776,18.989117,72.165130,...,High,5,Moderate,No,Yes,0,1.0,5.5,-2.275502,healthy
1,2,69,Female,163.207380,97.799859,36.716278,36.716278,110.148833,36.511417,85.598889,...,High,5,High,Yes,No,0,1.0,5.5,6.239340,healthy
2,3,46,Male,177.281966,80.687562,25.673050,25.673050,77.019151,25.587429,90.295030,...,High,4,Moderate,No,No,0,1.0,5.5,5.423737,healthy
3,4,32,Female,172.101255,63.142868,21.318480,21.318480,63.955440,21.177109,100.504211,...,High,1,NaN,No,Yes,0,1.0,5.5,8.388611,healthy
4,5,60,Female,163.608816,40.000000,14.943302,14.943302,44.829907,14.844299,69.021150,...,High,1,High,Yes,Yes,0,1.0,5.5,0.332622,healthy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,53,Male,177.202253,54.303671,17.293811,17.293811,51.881433,17.227616,88.740028,...,Moderate,1,High,No,Yes,0,1.0,5.5,3.477124,healthy
99996,99997,22,Male,180.802297,40.033853,12.246712,12.246712,36.740135,12.159473,103.659560,...,Moderate,5,NaN,Yes,No,0,1.0,5.5,1.609656,healthy
99997,99998,37,Male,185.540653,84.536847,24.556580,24.556580,73.669741,24.172944,98.920422,...,Low,5,NaN,No,No,0,1.0,5.5,-9.736463,healthy
99998,99999,72,Female,181.796786,56.923335,17.223362,17.223362,51.670087,17.715475,54.559079,...,Low,4,High,Yes,Yes,0,1.0,5.5,-4.779376,healthy
99999,100000,37,Male,175.716378,93.017286,30.125841,30.125841,90.377523,30.254072,70.743851,...,High,4,Moderate,Yes,No,0,1.0,5.5,-2.010351,diseased

In [39]:
data.describe()

# df.isnull().sum()

,survey_code,age,height,weight,bmi,bmi_estimated,bmi_scaled,bmi_corrected,waist_size,blood_pressure,...,water_intake,screen_time,stress_level,mental_health_score,income,meals_per_day,electrolyte_level,gene_marker_flag,environmental_risk_score,daily_supplement_dosage
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,92331.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,91530.000000,100000.000000,100000.0,89526.0,100000.0,100000.000000
mean,50000.500000,48.525990,170.023707,70.064862,24.493876,24.493876,73.481627,24.494140,84.933043,119.980149,...,2.006373,6.021525,4.991600,5.004680,4038.127284,2.998720,0.0,1.0,5.5,0.015726
std,28867.657797,17.886768,9.982798,14.693667,5.951069,5.951069,17.853206,5.954184,12.040314,15.015503,...,0.688868,2.933835,3.154997,3.164228,1930.025678,1.414786,0.0,0.0,0.0,5.764489
min,1.000000,18.000000,140.000000,40.000000,9.988495,9.988495,29.965484,9.893845,34.093185,59.128168,...,0.500000,0.000000,0.000000,0.000000,500.000000,1.000000,0.0,1.0,5.5,-9.999895
25%,25000.750000,33.000000,163.306615,59.856938,20.271405,20.271405,60.814215,20.271059,76.795185,109.812060,...,1.532011,3.971318,2.000000,2.000000,2665.402843,2.000000,0.0,1.0,5.5,-4.980501
50%,50000.500000,48.000000,170.016778,69.924141,24.156734,24.156734,72.470201,24.151699,84.957139,119.951794,...,2.000659,5.991171,5.000000,5.000000,4004.601345,3.000000,0.0,1.0,5.5,0.015589
75%,75000.250000,64.000000,176.728920,80.027418,28.258696,28.258696,84.776088,28.247648,93.018713,130.120621,...,2.473047,8.024470,8.000000,8.000000,5360.012694,4.000000,0.0,1.0,5.5,5.008424
max,100000.000000,79.000000,210.000000,139.250894,59.234792,59.234792,177.704377,59.142646,133.153631,184.439195,...,5.000000,16.000000,10.000000,10.000000,12029.409353,5.000000,0.0,1.0,5.5,9.999966

In [42]:
data=data.drop(["insurance","bmi_estimated","bmi_scaled","bmi_corrected","family_history","exercise_type","sleep_quality","family_history","job_type","environmental_risk_score","electrolyte_level","gene_marker_flag","mental_health_support","education_level"],axis=1)

In [44]:
data.describe()

,survey_code,age,height,weight,bmi,waist_size,blood_pressure,heart_rate,cholesterol,glucose,...,daily_steps,calorie_intake,sugar_intake,water_intake,screen_time,stress_level,mental_health_score,income,meals_per_day,daily_supplement_dosage
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,92331.000000,85997.000000,100000.000000,100000.000000,...,91671.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,91530.000000,100000.000000,100000.000000
mean,50000.500000,48.525990,170.023707,70.064862,24.493876,84.933043,119.980149,74.969177,189.966438,99.994538,...,7012.925748,2201.428579,60.047165,2.006373,6.021525,4.991600,5.004680,4038.127284,2.998720,0.015726
std,28867.657797,17.886768,9.982798,14.693667,5.951069,12.040314,15.015503,9.941668,29.981934,19.982828,...,2488.989356,400.516318,19.966850,0.688868,2.933835,3.154997,3.164228,1930.025678,1.414786,5.764489
min,1.000000,18.000000,140.000000,40.000000,9.988495,34.093185,59.128168,34.745092,58.410902,12.434931,...,1000.000000,527.172360,-27.882444,0.500000,0.000000,0.000000,0.000000,500.000000,1.000000,-9.999895
25%,25000.750000,33.000000,163.306615,59.856938,20.271405,76.795185,109.812060,68.275432,169.667738,86.461401,...,5320.858377,1932.278165,46.504292,1.532011,3.971318,2.000000,2.000000,2665.402843,2.000000,-4.980501
50%,50000.500000,48.000000,170.016778,69.924141,24.156734,84.957139,119.951794,75.046211,190.044579,99.986834,...,7004.285450,2200.992765,60.047905,2.000659,5.991171,5.000000,5.000000,4004.601345,3.000000,0.015589
75%,75000.250000,64.000000,176.728920,80.027418,28.258696,93.018713,130.120621,81.685914,210.222005,113.508722,...,8702.281300,2471.218160,73.476386,2.473047,8.024470,8.000000,8.000000,5360.012694,4.000000,5.008424
max,100000.000000,79.000000,210.000000,139.250894,59.234792,133.153631,184.439195,114.136041,319.875613,183.883548,...,18064.969543,3949.019017,141.514522,5.000000,16.000000,10.000000,10.000000,12029.409353,5.000000,9.999966

In [43]:
data.isnull().sum()

survey_code                    0
age                            0
gender                         0
height                         0
weight                         0
bmi                            0
waist_size                     0
blood_pressure              7669
heart_rate                 14003
cholesterol                    0
glucose                        0
insulin                    15836
sleep_hours                    0
work_hours                     0
physical_activity              0
daily_steps                 8329
calorie_intake                 0
sugar_intake                   0
alcohol_consumption        42387
smoking_level                  0
water_intake                   0
screen_time                    0
stress_level                   0
mental_health_score            0
occupation                     0
income                      8470
diet_type                      0
device_usage                   0
healthcare_access              0
sunlight_exposure              0
meals_per_day                  0
caffeine_intake            33261
pet_owner                      0
daily_supplement_dosage        0
target                         0
dtype: int64

In [47]:
data.to_csv('health_data_updated.csv', index=True)